"""Phase 5 tests: `lab cite`, `lab brief`, `lab report`.

    python3 -m pytest tests/test_phase5.py -q

`lab cite <unit> <key>` prints a value from a unit's values.tsv so a
program or an agent can paste it without retyping. `lab brief <unit>`
generates a brief block that carries keys and unit ids -- no digits.
`lab report <unit>` generates a report block tagged with the unit id.

The design's § The agent interface:
    "A brief carries keys and unit ids. A report carries a generated
     block. No digit crosses either boundary as a keystroke. `lab cite`
     is how a value reaches prose; a model asking for a number gets it
     from the program."
"""

import io
import pathlib
import re
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from lab import cite as cite_mod                                 # noqa: E402
from lab import brief as brief_mod                               # noqa: E402
from lab import report as report_mod                             # noqa: E402
from lab import unit as unit_mod                                 # noqa: E402
from lab import values as values_mod                             # noqa: E402
from lab import cli as cli_mod                                   # noqa: E402


def _run(fn, *args, **kwargs):
    out, err = io.StringIO(), io.StringIO()
    code = fn(*args, out, err, **kwargs)
    return code, out.getvalue(), err.getvalue()


# ---------------------------------------------------------------------------
# helpers -- build units in a temp tree
# ---------------------------------------------------------------------------

def make_unit(root, uid, slug, sealed=False, follows=None, body="",
              values_text=None, agents=None, refs=None, type_="run",
              title=None):
    """A loadable unit under `root/units/<uid>-<slug>/`."""
    path = root / "units" / f"{uid}-{slug}"
    (path / "run").mkdir(parents=True, exist_ok=True)
    fields = {"id": uid, "date": "2026-09-03", "type": type_,
              "title": title or slug, "refs": refs or [],
              "supersedes": [], "sealed": sealed}
    if follows is not None:
        fields = {**{k: v for k, v in fields.items() if k != "sealed"},
                  "follows": follows, "sealed": fields["sealed"]}
    if agents is not None:
        fields = {**{k: v for k, v in fields.items() if k != "sealed"},
                  "agents": agents, "sealed": fields["sealed"]}
    (path / "unit.md").write_text(
        "---\n" + unit_mod.format_front_matter(fields) + "\n---\n\n" + body,
        encoding="utf-8")
    if values_text is None:
        values_text = values_mod.EMPTY
    (path / "values.tsv").write_text(values_text, encoding="utf-8")
    return path


def _values_tsv(keys_values):
    """Build a values.tsv from a dict of {key: value}."""
    lines = [
        "# values.tsv -- GENERATED by `lab values` from run/. Do not edit.",
        "# source (none)",
    ]
    for k, v in keys_values.items():
        lines.append(f"{k}\t{v}")
    return "\n".join(lines) + "\n"


def _run_record_json(exit_code=0, wall_s=1.5):
    """A minimal lab_run JSON for testing."""
    import json
    return json.dumps({
        "schema_version": "v1.0",
        "unit": "units/0500-test",
        "runnable": "run/run.sh",
        "command": "/bin/sh -e run.sh",
        "argv": ["/bin/sh", "-e", "run.sh"],
        "cwd": "run",
        "exit_code": exit_code,
        "environment": {
            "lab_python": "v3.14.3",
            "os": "Darwin v25.6.0 arm64"
        },
        "meta": {
            "runnable_sha256": "abc123",
            "run_start": "2026-09-03T10:00:00Z",
            "run_end": "2026-09-03T10:00:01Z",
            "wall_s": wall_s
        }
    }, indent=2)


# ===========================================================================
# lab cite
# ===========================================================================

class TestCiteDirect:
    """Test cite_value and cite_run at the module level."""

    def test_known_key(self, tmp_path):
        vals = {"figures.ratio": "3.07", "figures.residual": "0.0184"}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals))
        result = cite_mod.cite_value("0500", "figures.ratio",
                                     cwd=tmp_path)
        assert result == "3.07"

    def test_missing_key_raises(self, tmp_path):
        vals = {"figures.ratio": "3.07"}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals))
        with pytest.raises(cite_mod.CiteError) as exc_info:
            cite_mod.cite_value("0500", "no.such.key", cwd=tmp_path)
        # The error message should list available keys
        assert "figures.ratio" in str(exc_info.value)

    def test_bad_unit_raises(self, tmp_path):
        (tmp_path / "units").mkdir(parents=True, exist_ok=True)
        with pytest.raises(Exception):
            cite_mod.cite_value("9999", "x", cwd=tmp_path)


class TestCiteRun:
    """Test cite via the run() entrypoint (CLI-shaped)."""

    def test_prints_value_no_decoration(self, tmp_path):
        vals = {"ladder.ratio": "3.07", "ladder.rows": "422"}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals))
        code, out, err = _run(cite_mod.run, "0500", "ladder.ratio",
                              cwd=tmp_path)
        assert code == 0
        # Output is the value, a newline, and nothing else
        assert out == "3.07\n"

    def test_bad_key_exits_1(self, tmp_path):
        vals = {"ladder.ratio": "3.07"}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals))
        code, out, err = _run(cite_mod.run, "0500", "no.such",
                              cwd=tmp_path)
        assert code == 1
        # stderr lists available keys
        assert "ladder.ratio" in err

    def test_bad_unit_exits_2(self, tmp_path):
        (tmp_path / "units").mkdir(parents=True, exist_ok=True)
        code, out, err = _run(cite_mod.run, "9999", "x", cwd=tmp_path)
        assert code == 2

    def test_string_value(self, tmp_path):
        vals = {"inputs.formula": '"0.137 log T + 0.443"'}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals))
        code, out, err = _run(cite_mod.run, "0500", "inputs.formula",
                              cwd=tmp_path)
        assert code == 0
        assert out == '"0.137 log T + 0.443"\n'

    def test_unit_prefix_resolution(self, tmp_path):
        vals = {"count": "42"}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals))
        code, out, err = _run(cite_mod.run, "0500", "count", cwd=tmp_path)
        assert code == 0
        assert out == "42\n"


# ===========================================================================
# lab brief
# ===========================================================================

class TestBriefDirect:
    """Test generate_brief at the module level."""

    def test_contains_unit_id(self, tmp_path):
        make_unit(tmp_path, "0500", "test", title="Test unit title")
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert "0500" in text

    def test_contains_title(self, tmp_path):
        make_unit(tmp_path, "0500", "test", title="Test unit title")
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert "Test unit title" in text

    def test_contains_keys(self, tmp_path):
        vals = {"figures.ratio": "3.07", "figures.residual": "0.0184"}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals))
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert "figures.ratio" in text
        assert "figures.residual" in text

    def test_no_raw_numeric_values(self, tmp_path):
        """The brief carries keys, not values. No digit crosses the boundary."""
        vals = {"figures.ratio": "3.07", "figures.residual": "0.0184",
                "census.rows": "422"}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals),
                  body="**Some numbers.** The ratio was 3.07.\n")
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        # The values 3.07, 0.0184, 422 must NOT appear in the brief.
        # We check the keys section specifically -- unit ids like 0500
        # are allowed as identifiers, not as numeric values.
        lines = text.split("\n")
        # Find lines that are in the "keys" section and contain values
        for val in ["3.07", "0.0184", "422"]:
            # The value should not appear anywhere in the brief
            assert val not in text, \
                f"value {val!r} leaked into the brief"

    def test_contains_type(self, tmp_path):
        make_unit(tmp_path, "0500", "test", type_="instrument-fix")
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert "instrument-fix" in text

    def test_contains_date(self, tmp_path):
        make_unit(tmp_path, "0500", "test")
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert "2026-09-03" in text

    def test_sealed_status(self, tmp_path):
        make_unit(tmp_path, "0500", "test", sealed=True)
        # Need to create a UNIT.sha256 for the sealed unit to be valid
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert "sealed" in text.lower()

    def test_follows_chain(self, tmp_path):
        make_unit(tmp_path, "0500", "first")
        make_unit(tmp_path, "0501", "second", follows="0500")
        text = brief_mod.generate_brief("0501", cwd=tmp_path)
        assert "0500" in text

    def test_agents_listed(self, tmp_path):
        agents = [{"id": "abc123", "role": "build",
                    "block": "transcript/b01.md"}]
        make_unit(tmp_path, "0500", "test", agents=agents)
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert "abc123" in text

    def test_paths_listed(self, tmp_path):
        make_unit(tmp_path, "0500", "test")
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert "unit.md" in text

    def test_is_fenced_block(self, tmp_path):
        """Output should be a fenced block, easy to paste into a prompt."""
        make_unit(tmp_path, "0500", "test")
        text = brief_mod.generate_brief("0500", cwd=tmp_path)
        assert text.startswith("```")
        assert text.rstrip().endswith("```")


class TestBriefRun:
    """Test brief via the run() entrypoint."""

    def test_exits_0(self, tmp_path):
        make_unit(tmp_path, "0500", "test")
        code, out, err = _run(brief_mod.run, "0500", cwd=tmp_path)
        assert code == 0
        assert "0500" in out

    def test_bad_unit_exits_2(self, tmp_path):
        (tmp_path / "units").mkdir(parents=True, exist_ok=True)
        code, out, err = _run(brief_mod.run, "9999", cwd=tmp_path)
        assert code == 2


# ===========================================================================
# lab report
# ===========================================================================

class TestReportDirect:
    """Test generate_report at the module level."""

    def test_tagged_with_unit_id(self, tmp_path):
        make_unit(tmp_path, "0500", "test")
        text = report_mod.generate_report("0500", cwd=tmp_path)
        assert "[0500]" in text

    def test_contains_title(self, tmp_path):
        make_unit(tmp_path, "0500", "test", title="A test report")
        text = report_mod.generate_report("0500", cwd=tmp_path)
        assert "A test report" in text

    def test_contains_type(self, tmp_path):
        make_unit(tmp_path, "0500", "test", type_="instrument-fix")
        text = report_mod.generate_report("0500", cwd=tmp_path)
        assert "instrument-fix" in text

    def test_contains_date(self, tmp_path):
        make_unit(tmp_path, "0500", "test")
        text = report_mod.generate_report("0500", cwd=tmp_path)
        assert "2026-09-03" in text

    def test_gate_results_from_run_record(self, tmp_path):
        """When a lab_run JSON exists, gate results appear."""
        path = make_unit(tmp_path, "0500", "test")
        (path / "run" / "lab_run.001.json").write_text(
            _run_record_json(exit_code=0, wall_s=1.5), encoding="utf-8")
        # Regenerate values.tsv to pick up the run record
        from lab import values as values_mod
        values_mod.write(path)
        text = report_mod.generate_report("0500", cwd=tmp_path)
        # Should mention exit code
        assert "exit" in text.lower() or "0" in text

    def test_values_summary(self, tmp_path):
        vals = {"a": "1", "b": "2", "c": "3"}
        make_unit(tmp_path, "0500", "test",
                  values_text=_values_tsv(vals))
        text = report_mod.generate_report("0500", cwd=tmp_path)
        # 3 keys
        assert "3" in text

    def test_agents_listed(self, tmp_path):
        agents = [{"id": "abc123", "role": "build",
                    "block": "transcript/b01.md"}]
        make_unit(tmp_path, "0500", "test", agents=agents)
        text = report_mod.generate_report("0500", cwd=tmp_path)
        assert "abc123" in text

    def test_refs_listed(self, tmp_path):
        make_unit(tmp_path, "0500", "test", refs=["0305", "0306"])
        text = report_mod.generate_report("0500", cwd=tmp_path)
        assert "0305" in text
        assert "0306" in text


class TestReportRun:
    """Test report via the run() entrypoint."""

    def test_exits_0(self, tmp_path):
        make_unit(tmp_path, "0500", "test")
        code, out, err = _run(report_mod.run, "0500", cwd=tmp_path)
        assert code == 0
        assert "[0500]" in out

    def test_bad_unit_exits_2(self, tmp_path):
        (tmp_path / "units").mkdir(parents=True, exist_ok=True)
        code, out, err = _run(report_mod.run, "9999", cwd=tmp_path)
        assert code == 2


# ===========================================================================
# CLI integration
# ===========================================================================

class TestCLIRegistration:
    """The three new subcommands are registered and callable."""

    def test_cite_subcommand_exists(self):
        parser = cli_mod.build_parser()
        # Should not error
        args = parser.parse_args(["cite", "0500", "key"])
        assert args.command == "cite"

    def test_brief_subcommand_exists(self):
        parser = cli_mod.build_parser()
        args = parser.parse_args(["brief", "0500"])
        assert args.command == "brief"

    def test_report_subcommand_exists(self):
        parser = cli_mod.build_parser()
        args = parser.parse_args(["report", "0500"])
        assert args.command == "report"


# ===========================================================================
# real units
# ===========================================================================

class TestRealUnits:
    """Run against the actual units in the tree."""

    REAL_ROOT = ROOT

    @pytest.fixture(autouse=True)
    def _check_units_exist(self):
        units = self.REAL_ROOT / "units"
        if not units.is_dir():
            pytest.skip("no units/ directory")

    def test_cite_0308_figures_matched(self):
        """lab cite 0308 figures.exempt.entry_302.tokens prints a value."""
        code, out, err = _run(cite_mod.run, "0308",
                              "figures.exempt.entry_302.tokens",
                              cwd=self.REAL_ROOT)
        assert code == 0
        assert out.strip()  # non-empty
        assert out == out.strip() + "\n"  # value + newline only

    def test_cite_0308_bad_key_lists_keys(self):
        code, out, err = _run(cite_mod.run, "0308", "no.such.key",
                              cwd=self.REAL_ROOT)
        assert code == 1
        assert "figures" in err  # at least some keys listed

    def test_brief_0308(self):
        code, out, err = _run(brief_mod.run, "0308", cwd=self.REAL_ROOT)
        assert code == 0
        assert "0308" in out
        # The brief must NOT contain raw numeric values from values.tsv
        # It should contain keys
        assert "figures" in out

    def test_brief_0309(self):
        code, out, err = _run(brief_mod.run, "0309", cwd=self.REAL_ROOT)
        assert code == 0
        assert "0309" in out

    def test_brief_0310(self):
        code, out, err = _run(brief_mod.run, "0310", cwd=self.REAL_ROOT)
        assert code == 0
        assert "0310" in out

    def test_report_0308(self):
        code, out, err = _run(report_mod.run, "0308", cwd=self.REAL_ROOT)
        assert code == 0
        assert "[0308]" in out

    def test_report_0309(self):
        code, out, err = _run(report_mod.run, "0309", cwd=self.REAL_ROOT)
        assert code == 0
        assert "[0309]" in out

    def test_report_0310(self):
        code, out, err = _run(report_mod.run, "0310", cwd=self.REAL_ROOT)
        assert code == 0
        assert "[0310]" in out

    def test_cite_0309_has_keys(self):
        """0309 has values; cite should work on it."""
        # Get a key from 0309's values.tsv
        u = unit_mod.load("0309", cwd=self.REAL_ROOT)
        if not u.values:
            pytest.skip("0309 has no values")
        key = next(iter(u.values))
        code, out, err = _run(cite_mod.run, "0309", key,
                              cwd=self.REAL_ROOT)
        assert code == 0
        assert out.strip()  # non-empty
