"""`UNIT.sha256` — one hash per file, then one digest over those lines.

PHASE 1 of `analysis/2026-09-02/lab_design.md`. The design's § The unit
gives this file two jobs in one sentence:

    "run/ is copied in as produced. The unit digest covers every file, so a
     re-run that reproduces gets a matching digest on everything except the
     declared volatile keys (timings, absolute paths, timestamps), which
     values.tsv marks with a `meta.` prefix and the digest excludes."

so a manifest line per file (that is the immutability guarantee `lab check`
enforces), and a digest over those lines from which the `meta.` keys are
excluded.

FORMAT. Comment lines, then one `path<TAB>sha256` line per file sorted by
path, then the digest line last:

    # UNIT.sha256 -- GENERATED by `lab seal`. ...
    question.md<TAB><hex>
    run/ladder.json<TAB><hex>
    unit.md<TAB><hex>
    values.tsv<TAB><hex>
    digest<TAB><hex>

Paths are POSIX and relative to the unit directory. `UNIT.sha256` itself is
not in its own manifest. Sorting is by path, so the manifest does not depend
on the order a directory walk happens to return.

DECISIONS taken here where the design is silent:

  - WHAT THE DIGEST HASHES. The manifest lines, joined by newlines with a
    trailing newline, with ONE substitution: `values.tsv` enters by its
    STABLE hash rather than its raw one. The stable hash is taken over
    values.tsv with its `#` header lines and its `meta.`-prefixed keys
    removed -- exactly the exclusion the design names. Every other file
    enters by the hash of its bytes as produced.
  - The stable hash is written out on its own comment line, so the digest
    can be recomputed by hand from the file without re-reading values.tsv.
  - WHY NOT ALSO STRIP `meta.` FROM `run/*.json`. The design says the
    digest covers every file, and a results JSON is covered as produced.
    Stripping volatile fields out of the JSONs themselves would make a
    non-bit-identical reproduction match, which is more than the design
    claims and more than the brief asks for. The reading chosen here is
    the one under which a BIT-IDENTICAL re-run always produces a matching
    digest, which raw hashes already give, and under which the `meta.`
    exclusion is implemented exactly where the design puts it: in
    values.tsv.
  - A unit holding a top-level file named `digest` is refused, because its
    manifest line would be indistinguishable from the digest line. The
    guard is cheap and the alternative is an ambiguous format.
  - Hidden files are covered like any other file. `run/.gitkeep` is in the
    manifest; a unit's contents are its contents.
"""

import hashlib
import pathlib

__all__ = [
    "DigestError",
    "MANIFEST",
    "file_hash",
    "stable_values_text",
    "unit_files",
    "manifest_lines",
    "digest_of",
    "render",
    "parse",
    "verify",
]

MANIFEST = "UNIT.sha256"
DIGEST_KEY = "digest"

HEADER = [
    "# UNIT.sha256 -- GENERATED by `lab seal`. One sha256 per file, sorted by",
    "# path, then the unit digest over those lines. A sealed unit is immutable:",
    "# `lab check` recomputes every line and reports each file that moved.",
    "# The digest takes values.tsv by its stable hash below -- its `#` header",
    "# lines and its `meta.` keys removed, per the design's § The unit -- and",
    "# every other file by the hash of its bytes as produced.",
]
STABLE_PREFIX = "# stable values.tsv "


class DigestError(Exception):
    """The manifest cannot be written, or cannot be read back."""


def _sha(data):
    return hashlib.sha256(data).hexdigest()


def file_hash(path):
    """sha256 of a file's bytes."""
    return _sha(pathlib.Path(path).read_bytes())


def stable_values_text(text):
    """values.tsv with its `#` header lines and its `meta.` keys removed.

    This is the design's exclusion: the volatile keys are the ones
    `lab values` prefixed with `meta.`, and the `#` lines carry the source
    JSONs' own sha256s, which are volatile for the same reason the keys are.
    """
    keep = [line for line in text.split("\n")
            if line and not line.startswith("#")
            and not line.startswith("meta.")]
    return "".join(line + "\n" for line in keep)


def unit_files(unit_path):
    """Every file in the unit except the manifest, sorted by POSIX relpath."""
    unit_path = pathlib.Path(unit_path)
    out = []
    for p in unit_path.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(unit_path).as_posix()
        if rel == MANIFEST:
            continue
        out.append(rel)
    out.sort()
    if DIGEST_KEY in out:
        raise DigestError(
            f"{unit_path}: a unit may not hold a top-level file named "
            f"{DIGEST_KEY!r}; its manifest line would read as the digest line")
    return out


def manifest_lines(unit_path):
    """([`path<TAB>hex` ...], stable hash of values.tsv or None)."""
    unit_path = pathlib.Path(unit_path)
    lines, stable = [], None
    for rel in unit_files(unit_path):
        raw = (unit_path / rel).read_bytes()
        lines.append(f"{rel}\t{_sha(raw)}")
        if rel == "values.tsv":
            stable = _sha(stable_values_text(
                raw.decode("utf-8")).encode("utf-8"))
    return lines, stable


def digest_of(lines, stable):
    """The unit digest: the manifest lines, values.tsv taken stably."""
    substituted = []
    for line in lines:
        rel = line.split("\t", 1)[0]
        if rel == "values.tsv" and stable is not None:
            substituted.append(f"{rel}\t{stable}")
        else:
            substituted.append(line)
    return _sha("".join(line + "\n" for line in substituted).encode("utf-8"))


def render(unit_path):
    """The full text of `UNIT.sha256` for a unit as it stands on disk."""
    lines, stable = manifest_lines(unit_path)
    out = list(HEADER)
    if stable is not None:
        out.append(STABLE_PREFIX + stable)
    out += lines
    out.append(f"{DIGEST_KEY}\t{digest_of(lines, stable)}")
    return "".join(line + "\n" for line in out)


def parse(text):
    """(ordered {relpath: hex}, stable hex or None, digest hex).

    Raises `DigestError` on a manifest this cannot read back.
    """
    files, stable, digest = {}, None, None
    for n, line in enumerate(text.split("\n"), 1):
        if not line.strip():
            continue
        if line.startswith(STABLE_PREFIX):
            stable = line[len(STABLE_PREFIX):].strip()
            continue
        if line.startswith("#"):
            continue
        if "\t" not in line:
            raise DigestError(f"{MANIFEST}: line {n} has no tab: {line[:60]!r}")
        key, value = line.split("\t", 1)
        value = value.strip()
        if key == DIGEST_KEY:
            digest = value
            continue
        if key in files:
            raise DigestError(f"{MANIFEST}: line {n} repeats {key!r}")
        files[key] = value
    if digest is None:
        raise DigestError(f"{MANIFEST}: no `{DIGEST_KEY}` line")
    return files, stable, digest


def verify(unit_path):
    """[problem, ...] for a sealed unit whose files no longer match.

    Empty means the unit is exactly what it was when it was sealed. Each
    problem is one line, already worded for a report.
    """
    unit_path = pathlib.Path(unit_path)
    manifest = unit_path / MANIFEST
    if not manifest.is_file():
        return [f"MISSING    {MANIFEST}  (front matter says sealed: true)"]
    try:
        recorded, rec_stable, rec_digest = parse(
            manifest.read_text(encoding="utf-8"))
    except DigestError as exc:
        return [f"UNREADABLE {exc}"]

    problems = []
    try:
        actual_lines, stable = manifest_lines(unit_path)
    except DigestError as exc:
        return [f"UNREADABLE {exc}"]
    actual = dict(line.split("\t", 1) for line in actual_lines)

    for rel, hexed in recorded.items():
        if rel not in actual:
            problems.append(f"MISSING    {rel}")
        elif actual[rel] != hexed:
            problems.append(f"CHANGED    {rel}  sealed {hexed[:12]}  "
                            f"now {actual[rel][:12]}")
    for rel in actual:
        if rel not in recorded:
            problems.append(f"UNSEALED   {rel}  (added since the seal)")

    if stable != rec_stable:
        problems.append(f"CHANGED    values.tsv  (stable content: sealed "
                        f"{str(rec_stable)[:12]}  now {str(stable)[:12]})")
    actual_digest = digest_of(actual_lines, stable)
    if actual_digest != rec_digest:
        problems.append(f"DIGEST     sealed {rec_digest[:12]}  "
                        f"now {actual_digest[:12]}")
    return problems
