"""`lab index` — regenerate INDEX.md and INDEX-values.tsv.

PHASE 3 of `analysis/2026-09-02/lab_design.md`. The design's § Counts says:

    "One generated INDEX.md at the project root owns every count, inventory
     and status: units by type, artifacts, Lean modules and theorems, open
     threads, the leaf ledger. Authored files lose their count slots and point
     at INDEX.md instead."

Phase 3 scopes INDEX.md to what the units tree provides: unit counts by type,
artifact counts (values.tsv key counts), sealed/unsealed status. Lean modules,
theorems, and the leaf ledger are outside the units tree and belong to a later
phase or extension.

The design's § The archive walks both ways says:

    "`lab index` generates the other direction as `INDEX-values.tsv` — one line
     per key, listing every unit whose prose cites it."

and:

    "It costs nothing extra to build: `lab check` already resolves every number
     in every unit to a key, so the reverse map is the same pass written out."

IDEMPOTENT. Both files depend only on the content of the units tree. Running
the command twice produces byte-identical files.

WHAT THE REVERSE MAP RECORDS. For each unit, the check logic finds which
numbers in the prose match which keys in that unit's values.tsv. The reverse
map inverts that: for each key, it lists every unit whose prose cites a value
that key holds. A key that is never cited by any unit's prose does not appear.

UNITS THAT FAIL TO LOAD ARE SKIPPED WITH A WARNING. A unit whose `unit.md` is
malformed or whose `values.tsv` is missing does not block the index; it is
reported on stderr and excluded. Every loadable unit appears in INDEX.md
regardless of whether its prose cites any values.
"""

import re
from collections import defaultdict
from decimal import Decimal, InvalidOperation

from . import check as check_mod
from . import exempt as exempt_mod
from .unit import UnitError, load, units_of, units_root

__all__ = ["index", "render_index_md", "render_reverse_map", "run"]


def _matched_keys(unit):
    """Return the set of keys in this unit's values.tsv that its prose cites.

    This is the inverse of `check.findings`: instead of collecting prose
    numbers with NO evidence, it collects the KEYS whose values have evidence
    in the prose. The matching logic is identical to `check.findings` —
    same NUM regex, same exemption spans, same rounding-aware comparison.
    """
    body = unit.body
    pool_by_key = {}  # key -> [Decimal, ...]
    for key, raw in unit.values.items():
        whole = check_mod._decimal(raw)
        if whole is not None:
            pool_by_key.setdefault(key, []).append(whole)
            continue
        # numbers inside string values, same logic as check.pool_parts
        import json as _json
        text = raw
        if len(raw) >= 2 and raw[0] == '"' and raw[-1] == '"':
            try:
                text = _json.loads(raw)
            except ValueError:
                text = raw
        if isinstance(text, str):
            for val in check_mod.numbers_in_string(text):
                pool_by_key.setdefault(key, []).append(val)

    if not pool_by_key:
        return set()

    spans = exempt_mod.spans(body)
    cited_keys = set()
    for m in check_mod.NUM.finditer(body):
        if any(lo <= m.start() < hi for lo, hi in spans):
            continue
        token = m.group(0)
        if exempt_mod.refs_id(token, unit.ids):
            continue
        try:
            want = Decimal(token.replace(",", ""))
        except InvalidOperation:
            continue
        for key, have in pool_by_key.items():
            if check_mod.matches(want, have):
                cited_keys.add(key)
    return cited_keys


def _load_all_units(root):
    """Load every unit under `root`. Returns (units, errors).

    `units` is a list of loaded Unit objects, sorted by id.
    `errors` is a list of (unit_name, error_message) pairs.
    """
    known = units_of(root)
    units, errors = [], []
    for uid, path in sorted(known.items()):
        try:
            units.append(load(str(path)))
        except UnitError as exc:
            errors.append((path.name, str(exc)))
    return units, errors


def render_index_md(units):
    """Render the INDEX.md content from a list of loaded units."""
    lines = [
        "<!-- INDEX.md -- GENERATED by `lab index` from units/. Do not edit. -->",
        "",
        "# Index",
        "",
    ]

    # --- totals ---
    total = len(units)
    sealed_count = sum(1 for u in units
                       if u.front_matter.get("sealed") is True)
    unsealed_count = total - sealed_count
    lines.append(f"{total} units: {sealed_count} sealed, "
                 f"{unsealed_count} unsealed.")
    lines.append("")

    # --- by type ---
    by_type = defaultdict(list)
    for u in units:
        by_type[u.front_matter.get("type", "unknown")].append(u)

    lines.append("## Units by type")
    lines.append("")
    for type_name in sorted(by_type):
        count = len(by_type[type_name])
        lines.append(f"### {type_name} ({count})")
        lines.append("")
        for u in sorted(by_type[type_name], key=lambda u: u.id):
            seal_mark = "sealed" if u.front_matter.get("sealed") is True \
                else "unsealed"
            title = u.front_matter.get("title", "")
            key_count = len(u.values)
            lines.append(f"- {u.id} {u.path.name} [{seal_mark}] "
                         f"-- {title} ({key_count} keys)")
        lines.append("")

    # --- artifact summary ---
    total_keys = sum(len(u.values) for u in units)
    lines.append("## Artifacts")
    lines.append("")
    lines.append(f"{total_keys} values.tsv keys across {total} units.")
    lines.append("")

    return "\n".join(lines)


def render_reverse_map(units):
    """Render INDEX-values.tsv: key -> unit ids whose prose cites that key.

    Only keys that are actually cited by at least one unit's prose appear.
    The output is sorted by key, and unit ids within each line are sorted.
    """
    # key -> set of unit ids
    reverse = defaultdict(set)
    for u in units:
        for key in _matched_keys(u):
            reverse[key].add(u.id)

    lines = [
        "# INDEX-values.tsv -- GENERATED by `lab index`. Do not edit.",
        "# One line per key, listing every unit whose prose cites its value.",
        "# key<TAB>unit_id[<TAB>unit_id...]",
    ]
    for key in sorted(reverse):
        ids = sorted(reverse[key])
        lines.append(f"{key}\t" + "\t".join(ids))
    return "\n".join(lines) + "\n"


def index(cwd=None):
    """Generate INDEX.md and INDEX-values.tsv. Returns (0, summary) or raises.

    Writes both files to the parent of the `units/` directory (the project
    root).
    """
    root = units_root(cwd=cwd)
    if root is None:
        raise UnitError("no units/ directory at or above the working directory")

    project_root = root.parent
    units, errors = _load_all_units(root)

    index_md = render_index_md(units)
    reverse_tsv = render_reverse_map(units)

    (project_root / "INDEX.md").write_text(index_md, encoding="utf-8")
    (project_root / "INDEX-values.tsv").write_text(reverse_tsv,
                                                    encoding="utf-8")

    # count reverse-map data lines
    data_lines = sum(1 for l in reverse_tsv.split("\n")
                     if l and not l.startswith("#"))

    return units, errors, data_lines


def run(out, err, cwd=None):
    """`lab index`: 0 success, 2 no units/ directory."""
    try:
        units, errors, reverse_count = index(cwd=cwd)
    except UnitError as exc:
        print(f"lab index: {exc}", file=err)
        return 2
    for name, msg in errors:
        print(f"WARNING    {name}: {msg}", file=err)
    sealed = sum(1 for u in units
                 if u.front_matter.get("sealed") is True)
    print(f"INDEX.md: {len(units)} unit(s) ({sealed} sealed); "
          f"INDEX-values.tsv: {reverse_count} key(s) in reverse map",
          file=out)
    return 0
