"""Locate a unit directory, parse its front matter, load its values.

The unit is `analysis/2026-09-02/lab_design.md` § The unit:

    units/0305-fixed-window-Lc/
      unit.md          authored prose + YAML front matter
      question.md      the transcript bracket the question was posed in
      run/             the code, its results, its logs -- as produced
      values.tsv       GENERATED: key<TAB>value, one line per leaf
      UNIT.sha256      GENERATED: hash per file, plus a unit digest

and the front matter it shows is

    ---
    id: 0305
    date: 2026-09-03
    type: run
    title: <one line>
    refs: [0302, 0304]
    supersedes: []
    sealed: false
    ---

FRONT MATTER IS NOT PARSED AS YAML. It is parsed as the flat subset the
design's example uses -- one `key: value` per line, where a value is a bare
scalar, a quoted scalar, `true`/`false`, or a flow list of bare scalars --
and every shape outside that subset raises `FrontMatterError` instead of
being guessed at. PyYAML is not a dependency, and a parser that silently
accepted a nested block would let a unit mean something the checker cannot
see.

PHASE 2c ADDS EXACTLY ONE NESTING: a key whose value is a block sequence of
FLAT MAPPINGS.

    agents:
      - id: a0a8bf60ac645202f
        role: build
        block: transcript/b01-phase2b-report.md

That is the design's § The fingerprint, drawn there and unparseable until
now. Unit 0308 records the finding -- "`agents:` cannot be written as the
design draws it ... It is written here as a flow list of colon-joined
triples" -- and the design's § The parser matches the spec settles the
direction: "The spec is the target and the parser moves to meet it."

The nesting is one level and no more. An item is `<indent>- key: value`, a
continuation is `<indent>  key: value`, an item's values are the same scalars
and flow lists a top-level value may be, and every other indented shape is
still refused by name: a nested mapping with no `- `, a second level of
nesting, an item whose indent disagrees with its siblings', a bare scalar
item, a tab. 0308's flattened `agents:` is LEFT AS IT IS, because that unit
is sealed and immutable; the shape a later unit writes is the one above.

DECISIONS taken here where the design is silent. Each is recorded because
the design names the front-matter shape without naming its grammar.

  - Scalars load as `str`, never as `int`. `id: 0305` has a leading zero
    that an int would eat, and the id is an identity rather than a
    quantity. `true`/`false` load as `bool`; a flow list loads as
    `list[str]`.
  - `True`, `False`, `yes`, `no`, `on`, `off`, `null` and `~` are
    REJECTED rather than resolved. Each has two defensible readings in
    YAML-adjacent formats, and guessing is the failure this parser exists
    to avoid.
  - Comment lines are rejected. Front matter is generated by `lab new`
    from Phase 1 onward, so it has exactly one shape and nothing to
    annotate.
  - A key with an empty value is rejected. Write `title: ''` to mean the
    empty string, so the intent is on the line.
  - `values.tsv` is REQUIRED for a unit to load. The design makes it part
    of the unit; a directory without one cannot answer the invariant, and
    reporting every number as unmatched (exit 1) would mistake a missing
    file for a wrong claim. Missing means the unit does not load: exit 2.
  - A unit argument resolves as a path first, then as a name under the
    nearest `units/` directory at or above the working directory, then as
    a unique id-or-slug prefix within it. An ambiguous prefix is an error.
"""

import os
import pathlib
import re

__all__ = [
    "FrontMatterError",
    "UnitError",
    "Unit",
    "parse_front_matter",
    "format_front_matter",
    "split_front_matter",
    "units_root",
    "units_of",
    "locate",
    "load",
]


class FrontMatterError(ValueError):
    """The front matter is outside the subset this parser accepts."""


class UnitError(Exception):
    """The unit directory cannot be found, or cannot be loaded."""


KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):(?: (.*))?$")
RESERVED = {"True", "False", "TRUE", "FALSE", "yes", "no", "Yes", "No",
            "YES", "NO", "on", "off", "On", "Off", "ON", "OFF",
            "null", "Null", "NULL", "~"}
BARE_ITEM = re.compile(r"^[^,\[\]'\"#]+$")
DELIM = "---"
ITEM = re.compile(r"^( +)- (\S.*)$")        # `  - id: a0`, the only nesting
CONT = "  "                                 # a continuation lines up past `- `


def _scalar(raw, where):
    """One front-matter scalar: bool, quoted string, or bare string."""
    if raw in ("true", "false"):
        return raw == "true"
    if raw in RESERVED:
        raise FrontMatterError(
            f"{where}: {raw!r} has more than one reading; write it quoted "
            f"(as a string) or as true/false")
    if raw[:1] in ("'", '"'):
        quote = raw[0]
        if len(raw) < 2 or raw[-1] != quote or quote in raw[1:-1]:
            raise FrontMatterError(f"{where}: unterminated {quote} quote")
        return raw[1:-1]
    if raw[:1] in ("|", ">", "&", "*", "!", "["):
        raise FrontMatterError(f"{where}: {raw[:1]!r} starts a YAML shape "
                               f"this parser does not accept")
    if " #" in raw:
        raise FrontMatterError(f"{where}: ' #' is an inline comment in YAML "
                               f"and a literal here; quote the value")
    return raw


def _flow_list(raw, where):
    """`[]` or `[a, b]` -- a flow sequence of bare scalars."""
    inner = raw[1:-1].strip()
    if not inner:
        return []
    items = []
    for chunk in inner.split(","):
        item = chunk.strip()
        if not item or not BARE_ITEM.match(item):
            raise FrontMatterError(
                f"{where}: {chunk.strip()!r} is not a bare list item; list "
                f"items may not be empty, quoted, nested or contain a comma")
        items.append(item)
    return items


def _value(raw, where):
    """One front-matter value: a flow list, or a scalar."""
    raw = raw.strip()
    if raw.startswith("["):
        if not raw.endswith("]"):
            raise FrontMatterError(f"{where}: unterminated flow list")
        return _flow_list(raw, where)
    return _scalar(raw, where)


def _pair(line, where):
    """`key: value` from one line's text. Raises `FrontMatterError`."""
    m = KEY.match(line)
    if not m:
        raise FrontMatterError(f"{where}: {line!r} is not `key: value`")
    key, raw = m.group(1), m.group(2)
    if raw is None or not raw.strip():
        raise FrontMatterError(
            f"{where}: key {key!r} has no value; write `{key}: ''` for the "
            f"empty string")
    return key, _value(raw, where)


def _block_sequence(lines, start):
    """([flat mapping, ...], lines consumed) for the block starting at `start`.

    PHASE 2c, and this is the ONLY nesting the parser accepts -- a sequence of
    flat mappings, which is what the design's § The fingerprint draws for
    `agents:` and nothing more:

        agents:
          - id: a0a8bf60ac645202f
            role: build
            block: transcript/b01-phase2b-report.md

    Returns `(None, 0)` when `start` does not open one, so the caller can
    raise its own "this key has no value" error. Every other indented shape
    is refused here by name, which is the strictness the module docstring
    records: reject what it cannot read rather than guessing at it.
    """
    if start >= len(lines):
        return None, 0
    first = ITEM.match(lines[start])
    if not first:
        return None, 0
    indent = first.group(1)
    cont = indent + CONT
    items, i = [], start
    while i < len(lines):
        line, where = lines[i], f"front matter line {i + 1}"
        if not line[:1].isspace():
            break
        if line != line.rstrip():
            raise FrontMatterError(f"{where}: trailing whitespace")
        if "\t" in line[:len(line) - len(line.lstrip())]:
            raise FrontMatterError(f"{where}: a tab in the indentation; this "
                                   f"parser indents with spaces only")
        m = ITEM.match(line)
        if m and m.group(1) == indent:
            key, value = _pair(m.group(2), where)
            items.append({key: value})
        elif line.startswith(cont) and not line[len(cont):len(cont) + 1] in \
                (" ", "-"):
            if not items:
                raise FrontMatterError(
                    f"{where}: a mapping line before the sequence's first "
                    f"`- ` item")
            key, value = _pair(line[len(cont):], where)
            if key in items[-1]:
                raise FrontMatterError(f"{where}: duplicate key {key!r} in "
                                       f"this item")
            items[-1][key] = value
        else:
            raise FrontMatterError(
                f"{where}: {line!r} is not an item of this block sequence. "
                f"An item is {indent!r} + '- key: value' and a continuation "
                f"is {cont!r} + 'key: value'; this parser accepts a sequence "
                f"of FLAT mappings and no deeper shape")
        i += 1
    return items, i - start


def parse_front_matter(text):
    """Parse the INNER lines of a front-matter block into a dict.

    `text` excludes the `---` delimiters; `split_front_matter` strips those.
    Raises `FrontMatterError` on anything outside the accepted subset.
    """
    lines = text.split("\n")
    out, i = {}, 0
    while i < len(lines):
        line, n = lines[i], i + 1
        where = f"front matter line {n}"
        if not line.strip():
            i += 1
            continue
        if line != line.rstrip():
            raise FrontMatterError(f"{where}: trailing whitespace")
        if line[:1].isspace():
            raise FrontMatterError(
                f"{where}: indented, and the line above it is not a key "
                f"opening a block sequence; this parser accepts flat "
                f"key/value lines and one nesting, `key:` followed by "
                f"`- key: value` items")
        if line.lstrip().startswith("#"):
            raise FrontMatterError(f"{where}: comments are not accepted")
        m = KEY.match(line)
        if not m:
            raise FrontMatterError(f"{where}: {line!r} is not `key: value`")
        key, raw = m.group(1), m.group(2)
        if key in out:
            raise FrontMatterError(f"{where}: duplicate key {key!r}")
        if raw is None or not raw.strip():
            block, used = _block_sequence(lines, i + 1)
            if block is None:
                raise FrontMatterError(
                    f"{where}: key {key!r} has no value; write `{key}: ''` "
                    f"for the empty string")
            out[key] = block
            i += 1 + used
            continue
        out[key] = _value(raw, where)
        i += 1
    return out


def format_front_matter(mapping):
    """Render a dict back to front-matter text, inverse of the parser.

    The output excludes the `---` delimiters, so
    `parse_front_matter(format_front_matter(d)) == d` for every dict this
    parser can produce.
    """
    lines = []
    for key, value in mapping.items():
        if not KEY.match(f"{key}: x"):
            raise FrontMatterError(f"{key!r} is not a usable key")
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        elif isinstance(value, list) and value \
                and all(isinstance(item, dict) for item in value):
            # PHASE 2c: the block sequence `_block_sequence` reads back.
            lines.append(f"{key}:")
            for item in value:
                if not item:
                    raise FrontMatterError(f"{key}: an empty mapping is not "
                                           f"an item of a block sequence")
                for j, (sub, sub_value) in enumerate(item.items()):
                    if not KEY.match(f"{sub}: x"):
                        raise FrontMatterError(f"{key}: {sub!r} is not a "
                                               f"usable key")
                    if isinstance(sub_value, bool):
                        text = "true" if sub_value else "false"
                    elif isinstance(sub_value, str):
                        text = _render_scalar(sub, sub_value)
                    else:
                        raise FrontMatterError(
                            f"{key}.{sub}: {type(sub_value).__name__} is not "
                            f"a flat-mapping value; use str or bool")
                    lines.append(f"  {'- ' if j == 0 else '  '}{sub}: {text}")
            continue
        elif isinstance(value, list):
            for item in value:
                if not isinstance(item, str) or not BARE_ITEM.match(item) \
                        or item != item.strip():
                    raise FrontMatterError(
                        f"{key}: {item!r} cannot be written as a bare list item")
            rendered = "[" + ", ".join(value) + "]"
        elif isinstance(value, str):
            rendered = _render_scalar(key, value)
        else:
            raise FrontMatterError(
                f"{key}: {type(value).__name__} is not a front-matter value; "
                f"use str, bool or list[str]")
        lines.append(f"{key}: {rendered}")
    return "\n".join(lines)


def _render_scalar(key, value):
    if "\n" in value:
        raise FrontMatterError(f"{key}: a value may not contain a newline")
    needs_quote = (
        value == ""
        or value != value.strip()
        or value in RESERVED
        or value in ("true", "false")
        or value[:1] in ("'", '"', "|", ">", "&", "*", "!", "[")
        or " #" in value
    )
    if not needs_quote:
        return value
    if "'" in value:
        raise FrontMatterError(
            f"{key}: {value!r} needs quoting and contains a single quote")
    return f"'{value}'"


def split_front_matter(text):
    """(front matter text, body text) for a `---`-delimited document."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != DELIM:
        raise FrontMatterError("the file does not open with a '---' line")
    for i in range(1, len(lines)):
        if lines[i].strip() == DELIM:
            return "\n".join(lines[1:i]), "\n".join(lines[i + 1:])
    raise FrontMatterError("the front matter block is not closed by '---'")


def _units_root(start):
    """Nearest `units/` directory at or above `start`, or None."""
    here = pathlib.Path(start).resolve()
    for candidate in [here, *here.parents]:
        if (candidate / "units").is_dir():
            return candidate / "units"
    return None


def units_root(cwd=None):
    """The nearest `units/` directory at or above `cwd`, or None.

    Phase 1 addition: `lab new` has to answer "where do units live" before
    any unit exists to locate, which is the same question `locate` already
    answered privately.
    """
    return _units_root(cwd or pathlib.Path.cwd())


ID_DIR = re.compile(r"^(\d{4,})-")


def units_of(root):
    """{id: path} for every `<id>-<slug>` directory under `root`.

    PHASE 2c. `lab new` already read the directory to allocate an id and
    `lab check` now has to answer "is 0307 a unit" for `follows:`, which is
    the same question asked twice. The directory is the ground truth for both,
    because it is the thing an id has to be unique against.
    """
    out = {}
    root = pathlib.Path(root)
    if not root.is_dir():
        return out
    for path in sorted(root.iterdir()):
        if not path.is_dir():
            continue
        m = ID_DIR.match(path.name)
        if m:
            out[m.group(1)] = path
    return out


def locate(arg, cwd=None):
    """Resolve a unit argument to its directory. Raises `UnitError`."""
    if not str(arg).strip():
        raise UnitError("no unit given")
    direct = pathlib.Path(arg)
    if direct.is_dir():
        return direct
    if direct.exists():
        raise UnitError(f"{arg}: not a directory")
    # A path was given and it does not exist. Only a bare name falls through
    # to the units/ lookup below: globbing an absolute or separator-bearing
    # pattern under units/ raises on 3.13+ and would mean nothing anyway.
    if direct.is_absolute() or os.sep in str(arg) or "/" in str(arg):
        raise UnitError(f"{arg}: no such directory")
    root = _units_root(cwd or pathlib.Path.cwd())
    if root is None:
        raise UnitError(f"{arg}: no such directory, and no units/ directory "
                        f"at or above the working directory")
    named = root / str(arg)
    if named.is_dir():
        return named
    hits = sorted(p for p in root.glob(f"{arg}*") if p.is_dir())
    if len(hits) == 1:
        return hits[0]
    if not hits:
        raise UnitError(f"{arg}: no such unit under {root}")
    raise UnitError(f"{arg}: ambiguous, matches "
                    + ", ".join(p.name for p in hits))


def read_values(path):
    """`values.tsv` as {key: raw value text}. Raises `UnitError`."""
    table = {}
    for n, line in enumerate(path.read_text(encoding="utf-8").split("\n"), 1):
        if not line.strip() or line.startswith("#"):
            continue
        if "\t" not in line:
            raise UnitError(f"{path}: line {n} has no tab: {line[:60]!r}")
        key, value = line.split("\t", 1)
        if key in table:
            raise UnitError(f"{path}: line {n} repeats key {key!r}")
        table[key] = value.strip()
    return table


class Unit:
    """A loaded unit: its path, its front matter, its prose, its values."""

    def __init__(self, path, front_matter, body, values):
        self.path = path
        self.front_matter = front_matter
        self.body = body
        self.values = values

    @property
    def id(self):
        return self.front_matter["id"]

    @property
    def ids(self):
        """Every id this unit names: its own, its refs, its supersedes."""
        out = {str(self.id)}
        for key in ("refs", "supersedes"):
            for item in self.front_matter.get(key, []) or []:
                out.add(str(item))
        return out

    def __repr__(self):
        return f"<Unit {self.id} at {self.path}>"


def load(arg, cwd=None):
    """Locate and load a unit. Raises `UnitError` on anything unloadable."""
    path = locate(arg, cwd=cwd)
    md = path / "unit.md"
    if not md.is_file():
        raise UnitError(f"{path}: no unit.md")
    try:
        fm_text, body = split_front_matter(md.read_text(encoding="utf-8"))
        front_matter = parse_front_matter(fm_text)
    except FrontMatterError as exc:
        raise UnitError(f"{md}: {exc}") from exc
    if "id" not in front_matter:
        raise UnitError(f"{md}: front matter has no `id`")
    if not isinstance(front_matter["id"], str):
        raise UnitError(f"{md}: `id` must be a scalar string, "
                        f"got {front_matter['id']!r}")
    tsv = path / "values.tsv"
    if not tsv.is_file():
        raise UnitError(f"{path}: no values.tsv; a unit without one cannot "
                        f"answer the invariant")
    return Unit(path, front_matter, body, read_values(tsv))
