/-
Transform — block G's geometry: the strip, the annulus, and what closes it.

`papers/Euler-Factor-Chain.md` § G is listed as **not formalised** in
`lean/BUILD.md`, and most of it is measurement (G2, G4, G5, G7 from O39) or
literature (G3 Jentzsch, G9 Hardy, G10 Odlyzko–te Riele). This file takes the
part that is geometry.

THE PICTURE. `z = b^(−s)` carries the s-plane to `ℂ*`. A vertical line
`Re s = σ` becomes the circle `|z| = b^(−σ)`, so the critical strip becomes an
annulus and the critical line becomes the circle of radius `b^(−1/2)`.

TWO GENERATORS, AND ONE OF THEM WAS MISSING FROM THE RECORD.

  * `s ↦ s + 2πi/log b` leaves `z` fixed. That is the pole lattice
    `Chain.sym_eq_zero_iff` proves, and it is why the strip becomes an annulus
    rather than a plane.
  * `s ↦ s + 1` sends `z ↦ z/b`. **This is the identification that closes the
    annulus into a torus**: `ℂ* / b^ℤ`. At `b = 2` it identifies
    `|z| = 0.5 ~ 1 ~ 2 ~ 4 …`, so every 2:1 annulus is a fundamental domain.

`papers/Euler-Factor-Chain.md` § G7 states the annulus `b^(−1) < |z| < b^(−1/2)`
and its modulus `(log b)/4π`, measured by O39. That annulus has ratio `√b`, so it
is **half a fundamental domain** of `ℂ* / b^ℤ`, whose modulus is `(log b)/2π`.
The record has the number and not the identification. See notes entry 84.

AND THE FUNCTIONAL EQUATION BECOMES AN INVERSION. `s ↦ 1 − s`, whose fixed set
is the critical line, becomes `z ↦ b^(−1)/z` — inversion in the circle
`|z| = b^(−1/2)`. Same fact as `EulerFactorChain.h_functional_equation`, read in
`z`.

WHAT IS NOT HERE. G1's Cauchy–Hadamard radius, G3's Jentzsch, G8's RH
equivalence, and every measured radius. Those stay observations, and G8 is an
equivalent restatement of RH "of identical difficulty" by the paper's own words.
-/
import Mathlib
import EulerFactorChain

open Complex

namespace Transform

variable {b : ℝ}

/-- **The map.** `z = b^(−s)` sends the vertical line `Re s = σ` to the circle
`|z| = b^(−σ)`. -/
theorem norm_zmap (hb : 0 < b) (s : ℂ) :
    ‖(b : ℂ) ^ (-s)‖ = b ^ (-s.re) := by
  rw [Complex.norm_cpow_eq_rpow_re_of_pos hb]
  simp

/-- The critical line lands on the circle of radius `b^(−1/2)`. -/
theorem norm_zmap_critical (hb : 0 < b) (γ : ℝ) :
    ‖(b : ℂ) ^ (-((1 : ℂ)/2 + γ * I))‖ = b ^ (-(1:ℝ)/2) := by
  rw [norm_zmap hb]
  norm_num

/-- **The deck transformation.** `s ↦ s + 1` becomes `z ↦ z / b`. This is the
identification that closes the annulus into a torus: `ℂ* / b^ℤ`. -/
theorem zmap_shift (hb : 0 < b) (s : ℂ) :
    (b : ℂ) ^ (-(s + 1)) = (b : ℂ) ^ (-s) / (b : ℂ) := by
  have h : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  rw [show -(s + 1) = -s + (-1 : ℂ) by ring, Complex.cpow_add _ _ h]
  simp [Complex.cpow_neg_one, div_eq_mul_inv]

/-- **The other generator.** `s ↦ s + 2πi/log b` leaves `z` fixed — that is the
pole lattice, and it is why the strip maps to an annulus rather than a plane. -/
theorem zmap_period (hb : 0 < b) (hb1 : b ≠ 1) (s : ℂ) :
    (b : ℂ) ^ (-(s + 2 * Real.pi * I / Real.log b)) = (b : ℂ) ^ (-s) := by
  have h : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  have hl : (Real.log b : ℂ) ≠ 0 := by
    exact_mod_cast Real.log_ne_zero_of_pos_of_ne_one hb hb1
  have hclog : Complex.log (b : ℂ) = (Real.log b : ℂ) := (Complex.ofReal_log hb.le).symm
  rw [Complex.cpow_def_of_ne_zero h, Complex.cpow_def_of_ne_zero h, hclog,
      show (Real.log b : ℂ) * -(s + 2 * (Real.pi : ℂ) * I / (Real.log b : ℂ))
        = (Real.log b : ℂ) * -s + -(2 * (Real.pi : ℂ) * I) from by field_simp; ring,
      Complex.exp_add, Complex.exp_neg, Complex.exp_two_pi_mul_I]
  simp

/-- **The functional equation, in `z`.** `s ↦ 1 − s` becomes `z ↦ b^(−1)/z`,
inversion in the circle `|z| = b^(−1/2)` — which is the critical line. -/
theorem zmap_functional_equation (hb : 0 < b) (s : ℂ) :
    (b : ℂ) ^ (-((1 : ℂ) - s)) = (b : ℂ) ^ (-(1 : ℂ)) / (b : ℂ) ^ (-s) := by
  have h : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  rw [show -((1:ℂ) - s) = -(1:ℂ) - (-s) by ring, Complex.cpow_sub _ _ h]

/-- **G7's modulus.** The annulus between the two radii has conformal modulus
`(log b)/4π`. Its ratio is `√b`, so it is half a fundamental domain of
`ℂ* / b^ℤ`, whose modulus is `(log b)/2π`. -/
theorem annulus_modulus (hb : 0 < b) :
    Real.log (b ^ (-(1:ℝ)/2) / b ^ (-(1:ℝ))) / (2 * Real.pi)
      = Real.log b / (4 * Real.pi) := by
  rw [← Real.rpow_sub hb, show -(1:ℝ)/2 - -(1:ℝ) = (1:ℝ)/2 by ring,
      Real.log_rpow hb]
  ring

/-! ## The modular parameter, and the isogeny classes

The lattice in `s` is generated by `1` (the shift, `zmap_shift`) and
`2πi/log b` (the period, `zmap_period`), so the modular parameter is
`τ = 2πi/log b`. For `b = 2` its imaginary part is `9.0647`, which is the
spacing `CONTEXT.md` § O18 measured for the dyadic alias comb.

Ladders that meet have rationally related `τ`, and the ratio is the meeting
exponents. Among bases 2–9 that gives the chains `{2,4,8}` and `{3,9}`:

```text
τ₂ = 9.0647   τ₄ = 4.5324 = τ₂/2   τ₈ = 3.0216 = τ₂/3
τ₃ = 5.7192   τ₉ = 2.8596 = τ₃/2
```

Base 6 joins neither, because `log 2 / log 6` is irrational and `6^n = 2^m` has
no solution above `n = 0` — sharing prime factors does not make ladders meet.
`Zeros.primeFactors_eq_of_meets` is the arithmetic side.

**No measurement supports any of this.** O53 and O54 tried to test `τ` as the
alias spacing on data and the statistic proved unstable — 0.27 to 1.94 at one
base with only the ceiling moving. See notes entry 85. What is below is
arithmetic. -/

/-- The torus `ℂ*/b^ℤ` has lattice `⟨1, 2πi/log b⟩` in `s`, so its modular
parameter is `τ = 2πi/log b`. This is its imaginary part. -/
noncomputable def tau (b : ℝ) : ℝ := 2 * Real.pi / Real.log b

/-- `τ` is exactly the period `zmap_period` uses. -/
theorem zmap_period_tau {b : ℝ} (hb : 0 < b) (hb1 : b ≠ 1) (s : ℂ) :
    (b : ℂ) ^ (-(s + (tau b : ℂ) * I)) = (b : ℂ) ^ (-s) := by
  have h : ((tau b : ℝ) : ℂ) * I = 2 * (Real.pi : ℂ) * I / (Real.log b : ℂ) := by
    unfold tau
    have hl : (Real.log b : ℂ) ≠ 0 := by
      exact_mod_cast Real.log_ne_zero_of_pos_of_ne_one hb hb1
    push_cast
    field_simp
  rw [h]
  exact zmap_period hb hb1 s

/-- **The power chain.** `τ(b^n) = τ(b)/n`. This is why `{2,4,8}` is one family:
`τ₄ = τ₂/2` and `τ₈ = τ₂/3`. -/
theorem tau_pow {b : ℝ} (hb : 1 < b) (n : ℕ) (hn : 0 < n) :
    tau (b ^ n) = tau b / n := by
  unfold tau
  rw [Real.log_pow]
  have : Real.log b ≠ 0 := Real.log_ne_zero_of_pos_of_ne_one (by linarith) hb.ne'
  field_simp

/-- **Meeting ladders have rationally related `τ`, and the ratio is the meeting
exponents.** If `b^n = c^m` then `τ(b)/τ(c) = n/m`. `Zeros.primeFactors_eq_of_meets`
records the arithmetic side: ladders meet only inside a prime-power chain. -/
theorem tau_ratio_of_meet {b c : ℝ} (hb : 1 < b) (hc : 1 < c)
    {n m : ℕ} (hm : 0 < m) (h : b ^ n = c ^ m) :
    tau b / tau c = n / m := by
  have hlb : Real.log b ≠ 0 := Real.log_ne_zero_of_pos_of_ne_one (by linarith) hb.ne'
  have hlc : Real.log c ≠ 0 := Real.log_ne_zero_of_pos_of_ne_one (by linarith) hc.ne'
  have key : (n : ℝ) * Real.log b = (m : ℝ) * Real.log c := by
    have := congrArg Real.log h
    rwa [Real.log_pow, Real.log_pow] at this
  unfold tau
  have hpi : Real.pi ≠ 0 := Real.pi_ne_zero
  field_simp
  linarith [key]

/-! ### The torus as an object

Everything above proves the two generator *maps*. Naming their quotient a torus
was a docstring reading, and this section replaces it with a constructed object:
`ℂ ⧸ ⟨1, τ(b)·i⟩`, which is `ℂ*/b^ℤ` read in `s`.

**What is proved:** the subgroup exists and contains both generators; the two
generators are ℝ-linearly independent, so the lattice has rank 2 and the
quotient is a torus rather than a cylinder; both identifications hold in the
quotient; the `z`-map descends past the pole lattice for *every* integer
multiple, not only for one period; and the deck transformation scales the
modulus by `b^(−n)`.

`periodLattice_discrete` then walks that to Mathlib's `ZLattice` API: the two
generators form an ℝ-basis of ℂ, so the subgroup is the ℤ-span of a basis and
carries the discrete topology. That is what makes the quotient a torus rather
than a quotient by an arbitrary subgroup.

**What is left unproved:** compactness of the quotient. `ZLattice` gives it from
here, and this file stops at discreteness.
-/

/-- The pole lattice alone: integer multiples of the period `τ(b)·i`. The
`z`-map is constant on its cosets, which is why the strip becomes an annulus. -/
noncomputable def poleLattice (b : ℝ) : AddSubgroup ℂ :=
  AddSubgroup.zmultiples ((tau b : ℂ) * I)

/-- The full period lattice in `s`: generated by `1`, the deck transformation,
and `τ(b)·i`, the pole lattice. -/
noncomputable def periodLattice (b : ℝ) : AddSubgroup ℂ :=
  AddSubgroup.closure {1, (tau b : ℂ) * I}

/-- **The torus.** `ℂ ⧸ ⟨1, τ(b)·i⟩` — the object `ℂ*/b^ℤ` names. -/
abbrev Torus (b : ℝ) : Type := ℂ ⧸ periodLattice b

theorem one_mem_periodLattice (b : ℝ) : (1 : ℂ) ∈ periodLattice b :=
  AddSubgroup.subset_closure (by simp)

theorem tauI_mem_periodLattice (b : ℝ) : ((tau b : ℂ) * I) ∈ periodLattice b :=
  AddSubgroup.subset_closure (by simp)

/-- `τ(b) > 0` for `b > 1`, which is what makes the second generator nonzero. -/
theorem tau_pos {b : ℝ} (hb : 1 < b) : 0 < tau b := by
  unfold tau
  have := Real.log_pos hb
  positivity

/-- **The lattice has rank 2.** The two generators are ℝ-linearly independent:
one is real, the other purely imaginary and nonzero. This is what separates a
torus from a cylinder, and it is the only place `b > 1` is needed. -/
theorem generators_indep {b : ℝ} (hb : 1 < b) (a c : ℝ)
    (h : (a : ℂ) + (c : ℂ) * ((tau b : ℂ) * I) = 0) : a = 0 ∧ c = 0 := by
  rw [Complex.ext_iff] at h
  simp at h
  obtain ⟨h1, h2⟩ := h
  refine ⟨h1, ?_⟩
  rcases h2 with h2 | h2
  · exact h2
  · exact absurd h2 (tau_pos hb).ne'

/-- The two generators as a family, for the basis construction below. -/
noncomputable def gens (b : ℝ) : Fin 2 → ℂ := ![1, (tau b : ℂ) * I]

/-- `generators_indep` in the form Mathlib's basis constructor wants. -/
theorem gens_linearIndependent {b : ℝ} (hb : 1 < b) : LinearIndependent ℝ (gens b) := by
  rw [gens, linearIndependent_fin2]
  constructor
  · show ((tau b : ℂ) * I) ≠ 0
    exact mul_ne_zero (Complex.ofReal_ne_zero.mpr (tau_pos hb).ne') I_ne_zero
  · intro a
    show a • ((tau b : ℂ) * I) ≠ 1
    intro ha
    have hre := congrArg Complex.re ha
    simp [Complex.real_smul] at hre

/-- **The lattice basis.** `⟨1, τ(b)·i⟩` is an ℝ-basis of ℂ, so the subgroup it
generates is a rank-2 ℤ-lattice in a 2-dimensional ℝ-space. -/
noncomputable def latticeBasis {b : ℝ} (hb : 1 < b) : Module.Basis (Fin 2) ℝ ℂ :=
  basisOfLinearIndependentOfCardEqFinrank (gens_linearIndependent hb)
    (by simp [Complex.finrank_real_complex])

theorem periodLattice_eq_span {b : ℝ} (hb : 1 < b) :
    periodLattice b = (Submodule.span ℤ (Set.range (latticeBasis hb))).toAddSubgroup := by
  rw [Submodule.span_int_eq_addSubgroupClosure]
  unfold periodLattice latticeBasis
  congr 1
  rw [coe_basisOfLinearIndependentOfCardEqFinrank]
  simp [gens, Matrix.range_cons, Matrix.range_empty, Set.pair_comm]

/-- **The lattice is discrete.** This is what upgrades `ℂ ⧸ periodLattice b`
from a quotient by a subgroup to a torus: a rank-2 ℤ-span of an ℝ-basis carries
the discrete topology, so the quotient is Hausdorff and the fibres are isolated.
The docstring above this section claimed this was left unproved; it is proved
here. -/
theorem periodLattice_discrete {b : ℝ} (hb : 1 < b) :
    DiscreteTopology (periodLattice b) := by
  rw [periodLattice_eq_span hb]
  infer_instance

/-- The deck transformation is an identity **in the torus**. -/
theorem torus_shift (b : ℝ) (s : ℂ) :
    ((s + 1 : ℂ) : Torus b) = (s : Torus b) := by
  rw [QuotientAddGroup.eq_iff_sub_mem]
  simpa using one_mem_periodLattice b

/-- The period is an identity **in the torus**. -/
theorem torus_period (b : ℝ) (s : ℂ) :
    ((s + (tau b : ℂ) * I : ℂ) : Torus b) = (s : Torus b) := by
  rw [QuotientAddGroup.eq_iff_sub_mem]
  simpa using tauI_mem_periodLattice b

/-- **The `z`-map descends past the whole pole lattice**, not just one period.
`zmap_period` is the `n = 1` case. -/
theorem zmap_period_zsmul {b : ℝ} (hb : 0 < b) (hb1 : b ≠ 1) (s : ℂ) (n : ℤ) :
    (b : ℂ) ^ (-(s + (n : ℂ) * ((tau b : ℂ) * I))) = (b : ℂ) ^ (-s) := by
  have h : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  have hl : (Real.log b : ℂ) ≠ 0 := by
    exact_mod_cast Real.log_ne_zero_of_pos_of_ne_one hb hb1
  have hclog : Complex.log (b : ℂ) = (Real.log b : ℂ) := (Complex.ofReal_log hb.le).symm
  rw [Complex.cpow_def_of_ne_zero h, Complex.cpow_def_of_ne_zero h, hclog,
    show (Real.log b : ℂ) * -(s + (n : ℂ) * ((tau b : ℂ) * I))
      = (Real.log b : ℂ) * -s + -((n : ℂ) * (2 * (Real.pi : ℂ) * I)) from by
        unfold tau; push_cast; field_simp; ring,
    Complex.exp_add, Complex.exp_neg, Complex.exp_int_mul_two_pi_mul_I]
  simp

/-- **The deck transformation scales the modulus by `b^(−n)`.** This is the
`b^ℤ` in `ℂ*/b^ℤ`: at `b = 2` it identifies `|z| = … 0.5 ~ 1 ~ 2 ~ 4 …`, so
every 2:1 annulus is a fundamental domain. -/
theorem zmap_shift_modulus {b : ℝ} (hb : 0 < b) (s : ℂ) (n : ℕ) :
    ‖(b : ℂ) ^ (-(s + n))‖ = ‖(b : ℂ) ^ (-s)‖ / b ^ n := by
  have h : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  rw [show -(s + (n : ℂ)) = -s + (-(n : ℂ)) by ring, Complex.cpow_add _ _ h,
    norm_mul]
  congr 1
  rw [show (-(n : ℂ)) = ((-(n : ℤ) : ℤ) : ℂ) by push_cast; ring,
    Complex.cpow_intCast, norm_zpow]
  simp [abs_of_pos hb]

/-- **The functional equation is inversion in the critical circle, as a
theorem.** `z ↦ b^(−1)/z` preserves modulus exactly on `|z| = b^(−1/2)` — the
image of the critical line. The geometric reading in `zmap_functional_equation`
was a docstring until here. -/
theorem inversion_fixes_circle {b : ℝ} (hb : 0 < b) {z : ℂ} (hz : z ≠ 0) :
    ‖(b : ℂ) ^ (-(1 : ℂ)) / z‖ = ‖z‖ ↔ ‖z‖ = b ^ (-(1 : ℝ) / 2) := by
  have hbc : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  have hzn : (0 : ℝ) < ‖z‖ := norm_pos_iff.mpr hz
  have hnum : ‖(b : ℂ) ^ (-(1 : ℂ))‖ = b ^ (-(1 : ℝ)) := by
    rw [Complex.norm_cpow_eq_rpow_re_of_pos hb]; simp
  rw [norm_div, hnum, div_eq_iff hzn.ne']
  constructor
  · intro h
    have hsq : ‖z‖ ^ (2 : ℕ) = b ^ (-(1 : ℝ)) := by rw [pow_two]; linarith
    have : (b ^ (-(1 : ℝ) / 2)) ^ (2 : ℕ) = b ^ (-(1 : ℝ)) := by
      rw [← Real.rpow_natCast (b ^ (-(1:ℝ)/2)) 2, ← Real.rpow_mul hb.le]
      norm_num
    nlinarith [Real.rpow_pos_of_pos hb (-(1:ℝ)/2), hzn]
  · intro h
    rw [h, ← Real.rpow_add hb]
    norm_num

/-! ### RH in this geometry

`inversion_fixes_circle` proves that `z ↦ b^(−1)/z` — the functional equation
read in `z` — fixes exactly the circle `|z| = b^(−1/2)`. That circle is the
image of the critical line. So the Riemann hypothesis becomes a statement about
fixed points:

    RH  ↔  every nontrivial zero is its own inversion partner on ℂ*/b^ℤ

Stated below against Mathlib's own `RiemannHypothesis`, and universally
quantified over every nontrivial zero. The base `b` is arbitrary above 1: the
criterion holds in every ladder's geometry at once, which is what makes it a
restatement rather than a base-dependent coincidence.

**This proves an equivalence and proves no zero.** It moves RH from the s-plane
to the torus and does nothing else. `O58_per_zero_exponent.py` measures the same
quantity on data, and a measurement is not a proof of anything here.
-/

/-- For `b > 1` the real power is injective in the exponent. -/
theorem rpow_left_inj {b : ℝ} (hb : 1 < b) (x y : ℝ) : b ^ x = b ^ y ↔ x = y := by
  have hb0 : (0 : ℝ) < b := by linarith
  have hl : Real.log b ≠ 0 := Real.log_ne_zero_of_pos_of_ne_one hb0 hb.ne'
  constructor
  · intro h
    have := congrArg Real.log h
    rw [Real.log_rpow hb0, Real.log_rpow hb0] at this
    exact mul_right_cancel₀ hl this
  · intro h; rw [h]

/-- The image of `s` under the `z`-map is never zero. -/
theorem zmap_ne_zero {b : ℝ} (hb : 0 < b) (s : ℂ) : (b : ℂ) ^ (-s) ≠ 0 := by
  have : ‖(b : ℂ) ^ (-s)‖ = b ^ (-s.re) := norm_zmap hb s
  have hpos : (0 : ℝ) < b ^ (-s.re) := Real.rpow_pos_of_pos hb _
  exact norm_pos_iff.mp (by rw [this]; exact hpos)

/-- **The critical line is exactly the fixed circle.** `Re s = 1/2` iff the image
`b^(−s)` lands on `|z| = b^(−1/2)`. -/
theorem on_critical_line_iff_norm {b : ℝ} (hb : 1 < b) (s : ℂ) :
    s.re = 1 / 2 ↔ ‖(b : ℂ) ^ (-s)‖ = b ^ (-(1 : ℝ) / 2) := by
  rw [norm_zmap (by linarith : (0:ℝ) < b) s, rpow_left_inj hb]
  constructor <;> intro h <;> linarith

/-- **RH's condition, as a fixed point of the inversion.** `Re s = 1/2` iff
`b^(−s)` is fixed in modulus by `z ↦ b^(−1)/z`, which `zmap_functional_equation`
identifies as `s ↦ 1 − s`. -/
theorem on_critical_line_iff_inversion_fixed {b : ℝ} (hb : 1 < b) (s : ℂ) :
    s.re = 1 / 2 ↔
      ‖(b : ℂ) ^ (-(1 : ℂ)) / (b : ℂ) ^ (-s)‖ = ‖(b : ℂ) ^ (-s)‖ := by
  have hb0 : (0 : ℝ) < b := by linarith
  rw [inversion_fixes_circle hb0 (zmap_ne_zero hb0 s), ← on_critical_line_iff_norm hb]

/-- **The Riemann hypothesis, restated on the torus.** Mathlib's
`RiemannHypothesis` holds exactly when every nontrivial zero of `ζ` is carried
by `z = b^(−s)` to a fixed point of the inversion `z ↦ b^(−1)/z`.

Holds for **every** `b > 1` simultaneously, and quantifies over **every**
nontrivial zero. It is an equivalence and it decides nothing. -/
theorem riemannHypothesis_iff_zeros_inversion_fixed {b : ℝ} (hb : 1 < b) :
    RiemannHypothesis ↔
      ∀ (s : ℂ), riemannZeta s = 0 → ¬(∃ n : ℕ, s = -2 * (n + 1)) → s ≠ 1 →
        ‖(b : ℂ) ^ (-(1 : ℂ)) / (b : ℂ) ^ (-s)‖ = ‖(b : ℂ) ^ (-s)‖ := by
  unfold RiemannHypothesis
  constructor
  · intro h s hz ht h1
    exact (on_critical_line_iff_inversion_fixed hb s).mp (h s hz ht h1)
  · intro h s hz ht h1
    exact (on_critical_line_iff_inversion_fixed hb s).mpr (h s hz ht h1)

/-! ### The strip is one fundamental domain, and the zeros live in it

Everything above relabels: it carries statements about `s` to statements about
`z` and back. This section is where the torus starts constraining rather than
relabelling, and it needs two facts that are about ζ rather than about the map.

**The strip is a fundamental domain.** Its edges `Re s = 0` and `Re s = 1` are a
single deck step apart, and `zmap_shift` carries one to the other. So the
critical strip is not merely *an* annulus in `z` — it is exactly one fundamental
domain of `ℂ*/b^ℤ`, for every `b > 1`. That is why this torus is the right
object rather than a convenient picture.

**The zeros are inside it.** Mathlib's `riemannZeta_ne_zero_of_one_le_re` puts
every zero at `Re s < 1`, hence strictly outside the inner circle `|z| = b^(−1)`.
-/

/-- `Re s = 0` lands on the unit circle. -/
theorem norm_zmap_zero_line {b : ℝ} (hb : 0 < b) {s : ℂ} (h : s.re = 0) :
    ‖(b : ℂ) ^ (-s)‖ = 1 := by
  rw [norm_zmap hb, h]
  simp

/-- **The critical strip is one fundamental domain of `ℂ*/b^ℤ`.** Its left edge
maps to `|z| = 1`, its right edge to `|z| = b^(−1)`, and the two are a single
deck step apart — `s ↦ s + 1`, which `zmap_shift` sends to `z ↦ z/b`. -/
theorem strip_is_fundamental_domain {b : ℝ} (hb : 1 < b) {s : ℂ} (h : s.re = 0) :
    ‖(b : ℂ) ^ (-s)‖ = 1 ∧ (s + 1).re = 1 ∧
      ‖(b : ℂ) ^ (-(s + 1))‖ = b ^ (-(1 : ℝ)) := by
  have hb0 : (0 : ℝ) < b := by linarith
  refine ⟨norm_zmap_zero_line hb0 h, by simp [h], ?_⟩
  rw [norm_zmap hb0]
  congr 1
  simp [h]

/-- **Every zero of ζ has `Re s < 1`**, from Mathlib's non-vanishing on the
closed half-plane `1 ≤ Re s`. -/
theorem zeros_re_lt_one {s : ℂ} (hz : riemannZeta s = 0) : s.re < 1 := by
  by_contra h
  exact riemannZeta_ne_zero_of_one_le_re (not_lt.mp h) hz

/-- **Every zero lies strictly outside the inner circle.** `Re s < 1` becomes
`|z| > b^(−1)` — the zeros are inside the fundamental annulus, on the far side
of the boundary the Euler product owns. -/
theorem zeros_outside_inner_circle {b : ℝ} (hb : 1 < b) {s : ℂ}
    (hz : riemannZeta s = 0) : b ^ (-(1 : ℝ)) < ‖(b : ℂ) ^ (-s)‖ := by
  have hb0 : (0 : ℝ) < b := by linarith
  rw [norm_zmap hb0]
  exact Real.rpow_lt_rpow_left_iff hb |>.mpr (by linarith [zeros_re_lt_one hz])

/-- **Every nontrivial zero has `0 < Re s`.** The functional equation reflects
Mathlib's non-vanishing on `1 ≤ Re s` across to the left edge: at a zero with
`Re s ≤ 0` every factor of `riemannZeta_one_sub` is nonzero except the cosine,
and the cosine's zeros are exactly the trivial zeros together with `s = 0`,
where `ζ(0) = −1/2`. -/
theorem zeros_re_pos {s : ℂ} (hz : riemannZeta s = 0)
    (ht : ¬(∃ n : ℕ, s = -2 * (n + 1))) : 0 < s.re := by
  by_contra hle
  push_neg at hle
  rcases eq_or_ne s 0 with rfl | hs0
  · rw [riemannZeta_zero] at hz; norm_num at hz
  set w : ℂ := 1 - s with hwdef
  have hwre : 1 ≤ w.re := by simp [hwdef, Complex.sub_re]; linarith
  have hwn : ∀ n : ℕ, w ≠ -n := by
    intro n h
    have : w.re = -(n : ℝ) := by rw [h]; simp
    have : (0 : ℝ) ≤ (n : ℝ) := Nat.cast_nonneg n
    linarith [hwre, ‹w.re = -(n:ℝ)›]
  have hw1 : w ≠ 1 := by
    intro h
    apply hs0
    have : (1 : ℂ) - s = 1 := h
    linear_combination -this
  have key := riemannZeta_one_sub hwn hw1
  rw [show (1 : ℂ) - w = s by rw [hwdef]; ring] at key
  have hzw : riemannZeta w ≠ 0 := riemannZeta_ne_zero_of_one_le_re hwre
  have hG : Complex.Gamma w ≠ 0 := Complex.Gamma_ne_zero hwn
  have hp : ((2 : ℂ) * (Real.pi : ℂ)) ^ (-w) ≠ 0 := by
    intro h
    rw [Complex.cpow_eq_zero_iff] at h
    have := h.1
    have hpi : (Real.pi : ℂ) ≠ 0 := by exact_mod_cast Real.pi_ne_zero
    simp [hpi] at this
  rw [hz] at key
  have hcos : Complex.cos ((Real.pi : ℂ) * w / 2) = 0 := by
    rcases mul_eq_zero.mp key.symm with h | h
    · rcases mul_eq_zero.mp h with h' | h'
      · rcases mul_eq_zero.mp h' with h'' | h''
        · rcases mul_eq_zero.mp h'' with h3 | h3
          · norm_num at h3
          · exact absurd h3 hp
        · exact absurd h'' hG
      · exact h'
    · exact absurd h hzw
  obtain ⟨k, hk⟩ := Complex.cos_eq_zero_iff.mp hcos
  have hpi : (Real.pi : ℂ) ≠ 0 := by exact_mod_cast Real.pi_ne_zero
  have hwk : w = 2 * (k : ℂ) + 1 := by field_simp at hk; exact hk
  have hkre : (1 : ℝ) ≤ 2 * (k : ℝ) + 1 := by
    have : w.re = 2 * (k : ℝ) + 1 := by rw [hwk]; simp
    linarith [hwre, this]
  have hk0 : 0 ≤ k := by exact_mod_cast (by linarith : (0:ℝ) ≤ (k:ℝ))
  have hsk : s = -2 * (k : ℂ) := by
    have : s = 1 - w := by rw [hwdef]; ring
    rw [this, hwk]; ring
  rcases eq_or_lt_of_le hk0 with h0 | hpos
  · exact hs0 (by rw [hsk, ← h0]; simp)
  · exact ht ⟨(k - 1).toNat, by
      rw [hsk]
      have : ((k - 1).toNat : ℂ) = (k : ℂ) - 1 := by
        have : ((k - 1).toNat : ℤ) = k - 1 := Int.toNat_of_nonneg (by omega)
        exact_mod_cast congrArg (fun z : ℤ => (z : ℂ)) this
      rw [this]; ring⟩

/-- **Every nontrivial zero lies in the open fundamental annulus.**
`b^(−1) < |z| < 1` — and `strip_is_fundamental_domain` says that annulus is
exactly one fundamental domain of `ℂ*/b^ℤ`. So the zeros of ζ sit inside a
single copy of the torus, for every base at once. -/
theorem zeros_in_fundamental_annulus {b : ℝ} (hb : 1 < b) {s : ℂ}
    (hz : riemannZeta s = 0) (ht : ¬(∃ n : ℕ, s = -2 * (n + 1))) :
    b ^ (-(1 : ℝ)) < ‖(b : ℂ) ^ (-s)‖ ∧ ‖(b : ℂ) ^ (-s)‖ < 1 := by
  have hb0 : (0 : ℝ) < b := by linarith
  refine ⟨zeros_outside_inner_circle hb hz, ?_⟩
  rw [norm_zmap hb0]
  have : b ^ (-s.re) < b ^ (0 : ℝ) :=
    (Real.rpow_lt_rpow_left_iff hb).mpr (by linarith [zeros_re_pos hz ht])
  simpa using this

/-- **RH, as a statement about one annulus.** Every nontrivial zero lies in the
fundamental annulus `b^(−1) < |z| < 1`; RH says every one of them lies on its
middle circle `|z| = b^(−1/2)`, which `inversion_fixes_circle` identifies as the
fixed set of `z ↦ b^(−1)/z`. The middle circle is the geometric mean of the two
boundaries, and the inversion swaps those boundaries. -/
theorem riemannHypothesis_iff_zeros_on_middle_circle {b : ℝ} (hb : 1 < b) :
    RiemannHypothesis ↔
      ∀ (s : ℂ), riemannZeta s = 0 → ¬(∃ n : ℕ, s = -2 * (n + 1)) → s ≠ 1 →
        ‖(b : ℂ) ^ (-s)‖ = b ^ (-(1 : ℝ) / 2) := by
  unfold RiemannHypothesis
  constructor
  · intro h s hz ht h1
    exact (on_critical_line_iff_norm hb s).mp (h s hz ht h1)
  · intro h s hz ht h1
    exact (on_critical_line_iff_norm hb s).mpr (h s hz ht h1)

/-! ## Axiom check

Every theorem here is ℂ-valued, so `Classical.choice` is the floor and stays.
`lean/BUILD.md` § Mathlib-free core has why that is the distinction to watch.
-/

/-- info: 'Transform.norm_zmap' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.norm_zmap

/-- info: 'Transform.norm_zmap_critical' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.norm_zmap_critical

/-- info: 'Transform.zmap_shift' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_shift

/-- info: 'Transform.zmap_period' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_period

/-- info: 'Transform.zmap_functional_equation' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_functional_equation

/-- info: 'Transform.annulus_modulus' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.annulus_modulus

/-- info: 'Transform.zmap_period_tau' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_period_tau

/-- info: 'Transform.tau_pow' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.tau_pow

/-- info: 'Transform.tau_ratio_of_meet' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.tau_ratio_of_meet

/-- info: 'Transform.one_mem_periodLattice' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.one_mem_periodLattice

/-- info: 'Transform.tauI_mem_periodLattice' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.tauI_mem_periodLattice

/-- info: 'Transform.tau_pos' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.tau_pos

/-- info: 'Transform.generators_indep' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.generators_indep

/-- info: 'Transform.torus_shift' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.torus_shift

/-- info: 'Transform.torus_period' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.torus_period

/-- info: 'Transform.zmap_period_zsmul' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_period_zsmul

/-- info: 'Transform.zmap_shift_modulus' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_shift_modulus

/-- info: 'Transform.inversion_fixes_circle' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.inversion_fixes_circle

/-- info: 'Transform.rpow_left_inj' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.rpow_left_inj

/-- info: 'Transform.zmap_ne_zero' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_ne_zero

/-- info: 'Transform.on_critical_line_iff_norm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.on_critical_line_iff_norm

/-- info: 'Transform.on_critical_line_iff_inversion_fixed' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.on_critical_line_iff_inversion_fixed

/-- info: 'Transform.riemannHypothesis_iff_zeros_inversion_fixed' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.riemannHypothesis_iff_zeros_inversion_fixed

/-- info: 'Transform.norm_zmap_zero_line' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.norm_zmap_zero_line

/-- info: 'Transform.strip_is_fundamental_domain' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.strip_is_fundamental_domain

/-- info: 'Transform.zeros_re_lt_one' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zeros_re_lt_one

/-- info: 'Transform.zeros_outside_inner_circle' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zeros_outside_inner_circle

/-- info: 'Transform.zeros_re_pos' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zeros_re_pos

/-- info: 'Transform.zeros_in_fundamental_annulus' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zeros_in_fundamental_annulus

/-- info: 'Transform.riemannHypothesis_iff_zeros_on_middle_circle' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.riemannHypothesis_iff_zeros_on_middle_circle



/-- info: 'Transform.gens_linearIndependent' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.gens_linearIndependent

/-- info: 'Transform.periodLattice_eq_span' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.periodLattice_eq_span

/-- info: 'Transform.periodLattice_discrete' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.periodLattice_discrete



end Transform
