/-
Transform — block G's geometry: the strip, the annulus, and what closes it.

`papers/Euler-Factor-Chain.md` § G is listed as **not formalised** in
`lean/BUILD.md`, and most of it is measurement (G2, G4, G5, G7 from O39) or
literature (G3 Jentzsch, G9 Hardy, G10 Odlyzko–te Riele). This file takes the
part that is geometry.

THE PICTURE. `z = b^(−s)` carries the s-plane to `ℂ*`. A vertical line
`Re s = σ` becomes the circle `|z| = b^(−σ)`, so the critical strip becomes an
annulus and the critical line becomes the circle of radius `b^(−1/2)`.

TWO GENERATORS, AND ONE OF THEM WAS MISSING FROM THE RECORD.

  * `s ↦ s + 2πi/log b` leaves `z` fixed. That is the pole lattice
    `Chain.sym_eq_zero_iff` proves, and it is why the strip becomes an annulus
    rather than a plane.
  * `s ↦ s + 1` sends `z ↦ z/b`. **This is the identification that closes the
    annulus into a torus**: `ℂ* / b^ℤ`. At `b = 2` it identifies
    `|z| = 0.5 ~ 1 ~ 2 ~ 4 …`, so every 2:1 annulus is a fundamental domain.

`papers/Euler-Factor-Chain.md` § G7 states the annulus `b^(−1) < |z| < b^(−1/2)`
and its modulus `(log b)/4π`, measured by O39. That annulus has ratio `√b`, so it
is **half a fundamental domain** of `ℂ* / b^ℤ`, whose modulus is `(log b)/2π`.
The record has the number and not the identification. See notes entry 84.

AND THE FUNCTIONAL EQUATION BECOMES AN INVERSION. `s ↦ 1 − s`, whose fixed set
is the critical line, becomes `z ↦ b^(−1)/z` — inversion in the circle
`|z| = b^(−1/2)`. Same fact as `EulerFactorChain.h_functional_equation`, read in
`z`.

WHAT IS NOT HERE. G1's Cauchy–Hadamard radius, G3's Jentzsch, G8's RH
equivalence, and every measured radius. Those stay observations, and G8 is an
equivalent restatement of RH "of identical difficulty" by the paper's own words.
-/
import Mathlib
import EulerFactorChain

open Complex

namespace Transform

variable {b : ℝ}

/-- **The map.** `z = b^(−s)` sends the vertical line `Re s = σ` to the circle
`|z| = b^(−σ)`. -/
theorem norm_zmap (hb : 0 < b) (s : ℂ) :
    ‖(b : ℂ) ^ (-s)‖ = b ^ (-s.re) := by
  rw [Complex.norm_cpow_eq_rpow_re_of_pos hb]
  simp

/-- The critical line lands on the circle of radius `b^(−1/2)`. -/
theorem norm_zmap_critical (hb : 0 < b) (γ : ℝ) :
    ‖(b : ℂ) ^ (-((1 : ℂ)/2 + γ * I))‖ = b ^ (-(1:ℝ)/2) := by
  rw [norm_zmap hb]
  norm_num

/-- **The deck transformation.** `s ↦ s + 1` becomes `z ↦ z / b`. This is the
identification that closes the annulus into a torus: `ℂ* / b^ℤ`. -/
theorem zmap_shift (hb : 0 < b) (s : ℂ) :
    (b : ℂ) ^ (-(s + 1)) = (b : ℂ) ^ (-s) / (b : ℂ) := by
  have h : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  rw [show -(s + 1) = -s + (-1 : ℂ) by ring, Complex.cpow_add _ _ h]
  simp [Complex.cpow_neg_one, div_eq_mul_inv]

/-- **The other generator.** `s ↦ s + 2πi/log b` leaves `z` fixed — that is the
pole lattice, and it is why the strip maps to an annulus rather than a plane. -/
theorem zmap_period (hb : 0 < b) (hb1 : b ≠ 1) (s : ℂ) :
    (b : ℂ) ^ (-(s + 2 * Real.pi * I / Real.log b)) = (b : ℂ) ^ (-s) := by
  have h : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  have hl : (Real.log b : ℂ) ≠ 0 := by
    exact_mod_cast Real.log_ne_zero_of_pos_of_ne_one hb hb1
  have hclog : Complex.log (b : ℂ) = (Real.log b : ℂ) := (Complex.ofReal_log hb.le).symm
  rw [Complex.cpow_def_of_ne_zero h, Complex.cpow_def_of_ne_zero h, hclog,
      show (Real.log b : ℂ) * -(s + 2 * (Real.pi : ℂ) * I / (Real.log b : ℂ))
        = (Real.log b : ℂ) * -s + -(2 * (Real.pi : ℂ) * I) from by field_simp; ring,
      Complex.exp_add, Complex.exp_neg, Complex.exp_two_pi_mul_I]
  simp

/-- **The functional equation, in `z`.** `s ↦ 1 − s` becomes `z ↦ b^(−1)/z`,
inversion in the circle `|z| = b^(−1/2)` — which is the critical line. -/
theorem zmap_functional_equation (hb : 0 < b) (s : ℂ) :
    (b : ℂ) ^ (-((1 : ℂ) - s)) = (b : ℂ) ^ (-(1 : ℂ)) / (b : ℂ) ^ (-s) := by
  have h : (b : ℂ) ≠ 0 := by exact_mod_cast hb.ne'
  rw [show -((1:ℂ) - s) = -(1:ℂ) - (-s) by ring, Complex.cpow_sub _ _ h]

/-- **G7's modulus.** The annulus between the two radii has conformal modulus
`(log b)/4π`. Its ratio is `√b`, so it is half a fundamental domain of
`ℂ* / b^ℤ`, whose modulus is `(log b)/2π`. -/
theorem annulus_modulus (hb : 0 < b) :
    Real.log (b ^ (-(1:ℝ)/2) / b ^ (-(1:ℝ))) / (2 * Real.pi)
      = Real.log b / (4 * Real.pi) := by
  rw [← Real.rpow_sub hb, show -(1:ℝ)/2 - -(1:ℝ) = (1:ℝ)/2 by ring,
      Real.log_rpow hb]
  ring

/-! ## The modular parameter, and the isogeny classes

The lattice in `s` is generated by `1` (the shift, `zmap_shift`) and
`2πi/log b` (the period, `zmap_period`), so the modular parameter is
`τ = 2πi/log b`. For `b = 2` its imaginary part is `9.0647`, which is the
spacing `CONTEXT.md` § O18 measured for the dyadic alias comb.

Ladders that meet have rationally related `τ`, and the ratio is the meeting
exponents. Among bases 2–9 that gives the chains `{2,4,8}` and `{3,9}`:

```text
τ₂ = 9.0647   τ₄ = 4.5324 = τ₂/2   τ₈ = 3.0216 = τ₂/3
τ₃ = 5.7192   τ₉ = 2.8596 = τ₃/2
```

Base 6 joins neither, because `log 2 / log 6` is irrational and `6^n = 2^m` has
no solution above `n = 0` — sharing prime factors does not make ladders meet.
`Zeros.primeFactors_eq_of_meets` is the arithmetic side.

**No measurement supports any of this.** O53 and O54 tried to test `τ` as the
alias spacing on data and the statistic proved unstable — 0.27 to 1.94 at one
base with only the ceiling moving. See notes entry 85. What is below is
arithmetic. -/

/-- The torus `ℂ*/b^ℤ` has lattice `⟨1, 2πi/log b⟩` in `s`, so its modular
parameter is `τ = 2πi/log b`. This is its imaginary part. -/
noncomputable def tau (b : ℝ) : ℝ := 2 * Real.pi / Real.log b

/-- `τ` is exactly the period `zmap_period` uses. -/
theorem zmap_period_tau {b : ℝ} (hb : 0 < b) (hb1 : b ≠ 1) (s : ℂ) :
    (b : ℂ) ^ (-(s + (tau b : ℂ) * I)) = (b : ℂ) ^ (-s) := by
  have h : ((tau b : ℝ) : ℂ) * I = 2 * (Real.pi : ℂ) * I / (Real.log b : ℂ) := by
    unfold tau
    have hl : (Real.log b : ℂ) ≠ 0 := by
      exact_mod_cast Real.log_ne_zero_of_pos_of_ne_one hb hb1
    push_cast
    field_simp
  rw [h]
  exact zmap_period hb hb1 s

/-- **The power chain.** `τ(b^n) = τ(b)/n`. This is why `{2,4,8}` is one family:
`τ₄ = τ₂/2` and `τ₈ = τ₂/3`. -/
theorem tau_pow {b : ℝ} (hb : 1 < b) (n : ℕ) (hn : 0 < n) :
    tau (b ^ n) = tau b / n := by
  unfold tau
  rw [Real.log_pow]
  have : Real.log b ≠ 0 := Real.log_ne_zero_of_pos_of_ne_one (by linarith) hb.ne'
  field_simp

/-- **Meeting ladders have rationally related `τ`, and the ratio is the meeting
exponents.** If `b^n = c^m` then `τ(b)/τ(c) = n/m`. `Zeros.primeFactors_eq_of_meets`
records the arithmetic side: ladders meet only inside a prime-power chain. -/
theorem tau_ratio_of_meet {b c : ℝ} (hb : 1 < b) (hc : 1 < c)
    {n m : ℕ} (hm : 0 < m) (h : b ^ n = c ^ m) :
    tau b / tau c = n / m := by
  have hlb : Real.log b ≠ 0 := Real.log_ne_zero_of_pos_of_ne_one (by linarith) hb.ne'
  have hlc : Real.log c ≠ 0 := Real.log_ne_zero_of_pos_of_ne_one (by linarith) hc.ne'
  have key : (n : ℝ) * Real.log b = (m : ℝ) * Real.log c := by
    have := congrArg Real.log h
    rwa [Real.log_pow, Real.log_pow] at this
  unfold tau
  have hpi : Real.pi ≠ 0 := Real.pi_ne_zero
  field_simp
  linarith [key]

/-! ## Axiom check

Every theorem here is ℂ-valued, so `Classical.choice` is the floor and stays.
`lean/BUILD.md` § Mathlib-free core has why that is the distinction to watch.
-/

/-- info: 'Transform.norm_zmap' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.norm_zmap

/-- info: 'Transform.norm_zmap_critical' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.norm_zmap_critical

/-- info: 'Transform.zmap_shift' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_shift

/-- info: 'Transform.zmap_period' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_period

/-- info: 'Transform.zmap_functional_equation' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_functional_equation

/-- info: 'Transform.annulus_modulus' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.annulus_modulus

/-- info: 'Transform.zmap_period_tau' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.zmap_period_tau

/-- info: 'Transform.tau_pow' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.tau_pow

/-- info: 'Transform.tau_ratio_of_meet' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Transform.tau_ratio_of_meet

end Transform
