name = "stage3"
defaultTargets = ["Stage3"]

[[require]]
name = "PrimeNumberTheoremAnd"
git = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd"
rev = "47fa48680663df41146704d02a5b092d792bd5b9"

[[lean_lib]]
name = "Stage3"
